version: '0.1'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password  # Replace 'password' with your desired password
    volumes:
      - neo4j_data:/data

  python:
    build: .
    volumes:
      - .:/app
    depends_on:
      - neo4j

volumes:
  neo4j_data: